source/accounts/urls.py
from django.urls import path, re_path

from accounts.views import RegisterView, UserDetailView, UserChangeView, UserPasswordChangeView, UserList, UserAdd, \
    TokenDelete, UserResults
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/<str:token>/', RegisterView.as_view(), name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('change/', UserChangeView.as_view(), name='change'),
    path('user/add/', UserAdd.as_view(), name='user_add'),
    path('user/group/<int:group_pk>/results/', UserResults.as_view(), name='user_results'),
    path('user/group/<int:group_pk>/period/<int:period_pk>/results/', UserResults.as_view(), name='user_results_period'),
    path('token/<int:pk>/delete/', TokenDelete.as_view(), name='token_delete'),
    path('password_change/', UserPasswordChangeView.as_view(), name='password_change'),
    path("password_reset/", PasswordResetView.as_view(), name="password_reset"),
    re_path(r'^users/(?P<is_filter>registered|not_registered)/$', UserList.as_view(), name='users_list_is_filter'),
]

source/crm_attractor/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('accounts.urls')),
                  path('', include('webapp.urls')),
                  path('tinymce/', include('tinymce.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views import IndexView, GroupsList, GroupView, LessonView, MaterialView, MaterialList, \
    PeriodCreate, PeriodDelete, LessonCreate, LessonUpdate, LessonDelete, LessonGroupCreate, LanguageCreate, \
    LanguageDelete, GroupCreate, GroupUpdate, GroupDelete, MaterialCreate, MaterialUpdate, MaterialDelete, \
    MaterialSearchCreate, LinkBroadcastCreate, LinkBroadcastDelete, WorkUserCreate, WorkUserUpdate, WorkUserCheck, \
    LessonUpdateDeadlineTask, WorkLessonCheck, PeriodView, WorkView

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('lesson/<int:lesson_pk>/', LessonView.as_view(), name='lesson_view'),
    path('lesson/create/', LessonCreate.as_view(), name='lesson_create'),
    path('lesson/<int:group_pk>/create/', LessonGroupCreate.as_view(), name='lesson_group_create'),
    path('lesson/<int:lesson_pk>/update/', LessonUpdate.as_view(), name='lesson_update'),
    path('lesson/<int:lesson_pk>/update/deadline_task/', LessonUpdateDeadlineTask.as_view(),
         name='lesson_update_deadline_task'),
    path('lesson/<int:lesson_pk>/delete/', LessonDelete.as_view(), name='lesson_delete'),

    path('group/', GroupsList.as_view(), name='groups_list'),
    path('group/<int:group_pk>/', GroupView.as_view(), name='group_view'),
    path('group/<int:group_pk>/period/<int:period_pk>/', GroupView.as_view(), name='group_view_period_pk'),
    path('group/<int:language_pk>/create/', GroupCreate.as_view(), name='group_create'),
    path('group/<int:group_pk>/update/', GroupUpdate.as_view(), name='group_update'),
    path('group/<int:group_pk>/delete/', GroupDelete.as_view(), name='group_delete'),

    path('materials/', MaterialList.as_view(), name='materials_list'),
    path('material/<int:material_pk>/', MaterialView.as_view(), name='material_view'),
    path('material/<int:group_pk>/lesson/<int:lesson_pk>/type/<str:type>/create/', MaterialCreate.as_view(),
         name='material_create'),
    path('material/<int:group_pk>/lesson/<int:lesson_pk>/type/<str:type>/create_search/',
         MaterialSearchCreate.as_view(),
         name='material_search_create'),
    path('material/<int:material_pk>/update/', MaterialUpdate.as_view(), name='material_update'),
    path('material/<int:material_pk>/delete/', MaterialDelete.as_view(), name='material_delete'),

    path('language/create/', LanguageCreate.as_view(), name='language_create'),
    path('language/<int:language_pk>/delete/', LanguageDelete.as_view(), name='language_delete'),

    path('period/create/<int:group_pk>/', PeriodCreate.as_view(), name='period_create'),
    path('period/delete/<int:pk>/', PeriodDelete.as_view(), name='period_delete'),
    path('period/<int:pk>/', PeriodView.as_view(), name='period_results'),

    path('work/<int:pk>/', WorkView.as_view(), name='work_view'),
    path('work/lesson/<int:lesson_pk>/create/', WorkUserCreate.as_view(), name='work_create'),
    path('work/<int:work_pk>/update/', WorkUserUpdate.as_view(), name='work_update'),
    path('work/<int:work_pk>/verification/', WorkUserCheck.as_view(), name='work_check'),
    path('work/lesson/<int:lesson_pk>/lesson_check/', WorkLessonCheck.as_view(), name='work_lesson_check'),

    path('link_broadcast/lesson/<int:lesson_pk>/create/', LinkBroadcastCreate.as_view(),
         name='link_broadcast_create'),
    path('link_broadcast/<int:link_broadcast_pk>/delete/', LinkBroadcastDelete.as_view(),
         name='link_broadcast_delete'),
]

source/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from secrets import token_urlsafe

from django.db.models import Avg
from math import ceil

ROLE_TEACHER = 'teacher'
ROLE_ADMIN = 'admin'
ROLE_STUDENT = 'student'
ROLES_USER = [
    (ROLE_TEACHER, 'Учитель'),
    (ROLE_ADMIN, 'Администратор'),
    (ROLE_STUDENT, 'Студент'),
]


class RoleAndGroup(models.Model):
    token = models.CharField(max_length=50, unique=True, default=token_urlsafe)
    created_at = models.DateTimeField(auto_now_add=True)
    is_activation = models.BooleanField(default=False)
    groups = models.ManyToManyField('webapp.Group', related_name='role_and_group', blank=True, verbose_name="Группы")
    user_role = models.CharField(choices=ROLES_USER, max_length=20, verbose_name='Тип')
    data_start = models.DateField(verbose_name='Дата начала учебы')

    def __str__(self):
        return f"{self.token} {self.user_role} {self.is_activation} {self.created_at}"


class User(AbstractUser):
    birth_date = models.DateField(null=True, verbose_name='Дата рождения')
    avatar = models.ImageField(null=True, blank=True, verbose_name='Фотография')
    role_and_group = models.OneToOneField('accounts.RoleAndGroup', related_name='user', on_delete=models.PROTECT)

    def get_total_results(self, period_pk):
        total = self.user_works.filter(lesson__period_id=period_pk).exclude(lesson__type_lesson='control').aggregate(
            total=Avg('grade'))['total'] * 5
        work_control = self.user_works.filter(lesson__period_id=period_pk, lesson__type_lesson='control').first()
        if work_control:
            total += work_control.grade
        return ceil(total)

    def is_admin(self):
        return self.role_and_group.user_role == ROLE_ADMIN

    def is_teacher(self):
        return self.role_and_group.user_role == ROLE_TEACHER

    def is_student(self):
        return self.role_and_group.user_role == ROLE_STUDENT

    def get_groups(self):
        return self.role_and_group.groups.all()

source/webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Language(models.Model):
    name_language = models.CharField(max_length=200, unique=True, verbose_name='Название языка')

    def __str__(self):
        return "{}. {}".format(self.pk, self.name_language)


class Group(models.Model):
    number_group = models.IntegerField(verbose_name='Номер группы')
    data_start = models.DateField(verbose_name='Дата запуска группы')
    color = models.CharField(max_length=20, verbose_name="Цвет группы")
    data_end = models.DateField(null=True, blank=True, verbose_name='Дата выпуска группы')
    language = models.ForeignKey('webapp.Language', related_name='groups', on_delete=models.PROTECT,
                                 verbose_name='Язык')
    users = models.ManyToManyField(get_user_model(), related_name='groups_language', through='webapp.GroupUser',
                                   through_fields=('group', 'user'), blank=True)
    is_activation = models.BooleanField(default=True)

    def __str__(self):
        return "{}№{} ({}-{}) ".format(self.language.name_language, self.number_group, self.data_start, self.data_end)


class Period(models.Model):
    number_period = models.IntegerField(verbose_name='Номер периода')
    data_start = models.DateField(verbose_name='Дата начала периода')
    data_end = models.DateField(verbose_name='Дата окончания периода')
    group = models.ForeignKey('webapp.Group', related_name='periods', on_delete=models.PROTECT,
                              verbose_name='Группа')

    def __str__(self):
        return "{}. {} #{}  ({}-{})".format(self.pk, self.group, self.number_period, self.data_start, self.data_end)


TYPE_TASK = 'task'
TYPE_MATERIAL = 'material'
TYPES_MATERIAL = [
    (TYPE_TASK, 'Задание'),
    (TYPE_MATERIAL, 'Материал'),
]


class Material(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    content = models.TextField(null=True, blank=True, verbose_name='Содержимое')
    group = models.ForeignKey('webapp.Group', related_name='material', on_delete=models.PROTECT,
                              verbose_name='Группа')
    lesson = models.ForeignKey('webapp.Lesson', on_delete=models.PROTECT, related_name='materials', verbose_name='Урок')
    type_material = models.CharField(choices=TYPES_MATERIAL, max_length=20, verbose_name='Тип')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Время изменения")

    def __str__(self):
        return "{}. {}".format(self.pk, self.title)


TYPE_LESSON = 'lesson'
TYPE_WEBINAR = 'webinar'
TYPE_CONTROL = 'control'
CHOICES_TYPES_LESSON = ((TYPE_LESSON, 'Занятие'), (TYPE_WEBINAR, 'Вебинар'), (TYPE_CONTROL, 'Контрольная'))


class Lesson(models.Model):
    number = models.IntegerField(default=1, verbose_name='Номер урока')
    data_start = models.DateTimeField(verbose_name='Время начала урока')
    theme = models.CharField(max_length=200, null=True, blank=True, verbose_name='Тема урока')
    deadline_task = models.DateTimeField(null=True, blank=True, verbose_name='Дедлайн задания')
    type_lesson = models.CharField(choices=CHOICES_TYPES_LESSON, null=True, verbose_name='Тип урока')
    period = models.ForeignKey('webapp.Period', related_name='lessons', on_delete=models.PROTECT,
                               verbose_name='Период')

    def __str__(self):
        return "{}. {} ({})".format(self.pk, self.theme, self.data_start)

    def get_razdatka(self):
        return self.materials.filter(type_material=TYPE_MATERIAL).order_by('-created_at').first()

    def get_task(self):
        return self.materials.filter(type_material=TYPE_TASK).order_by('-created_at').first()


class LinkBroadcast(models.Model):
    link = models.CharField(max_length=200, verbose_name='Ссылка')
    lesson = models.ForeignKey('webapp.Lesson', related_name='links_broadcast', on_delete=models.PROTECT,
                               verbose_name='Урок')

    def __str__(self):
        return "{}. {}".format(self.pk, self.link)


class Work(models.Model):
    grade = models.FloatField(verbose_name='Оценка', default=0)
    work = models.FileField(null=True, blank=True, verbose_name='Файл')
    link = models.CharField(max_length=200, null=True, blank=True, verbose_name='Ссылка')
    review = models.TextField(null=True, blank=True, verbose_name='Рецензия')
    lesson = models.ForeignKey('webapp.Lesson', related_name='lesson_works', on_delete=models.CASCADE,
                               verbose_name='Урок')
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='user_works',
                             verbose_name='Пользователь')
    status = models.BooleanField(default=False, verbose_name='Проверена')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Время загрузки")


class GroupUser(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='user_groups',
                             verbose_name='Пользователь')
    group = models.ForeignKey('webapp.Group', related_name='group_users', on_delete=models.PROTECT,
                              verbose_name='Группа')
    data_start = models.DateField(verbose_name='Дата начала учебы')
    data_end = models.DateField(null=True, blank=True, verbose_name='Дата окончания учебы')

source/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.forms import widgets
from accounts.models import RoleAndGroup
from webapp.models import Group


class RoleAndGroupForm(forms.ModelForm):
    groups = forms.ModelMultipleChoiceField(queryset=Group.objects.filter(is_activation=True), required=False,
                                            label="Группы",
                                            widget=forms.CheckboxSelectMultiple(attrs={'class': 'mb-2', }))

    class Meta:
        model = RoleAndGroup
        fields = ['user_role', 'groups', 'data_start']
        widgets = {
            'user_role': widgets.Select(attrs={
                'class': 'form-select w-50'
            }),
            'data_start': forms.DateInput(attrs={
                'type': 'date',
                'class': 'form-control w-50'
            }, format='%Y-%m-%d')
        }


class MyUserCreationForm(UserCreationForm):
    password1 = forms.CharField(label="Пароль", strip=False,
                                widget=forms.PasswordInput(attrs={'class': 'form-control w-50'}))
    password2 = forms.CharField(label="Подтверждение пароля",
                                widget=forms.PasswordInput(attrs={'class': 'form-control w-50'}), strip=False)

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ['username', 'password1', 'password2', 'first_name', 'last_name', 'email', 'birth_date']
        widgets = {
            'username': widgets.TextInput(attrs={
                'class': 'form-control w-50'
            }),
            'first_name': widgets.TextInput(attrs={
                'class': 'form-control w-50'
            }),
            'last_name': widgets.TextInput(attrs={
                'class': 'form-control w-50'
            }),
            'email': widgets.EmailInput(attrs={
                'class': 'form-control w-50'
            }),
            'birth_date': widgets.DateInput(attrs={
                'type': 'date',
                'class': 'form-control w-50'
            }, format='%Y-%m-%d'),
            'avatar': widgets.FileInput(attrs={
                'class': 'form-control rounded-pill mb-3 w-50'
            })
        }


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email', 'birth_date', 'avatar']
        labels = {'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email'}
        widgets = {
            'first_name': widgets.TextInput(attrs={
                'class': 'form-control w-50'
            }),
            'last_name': widgets.TextInput(attrs={
                'class': 'form-control w-50'
            }),
            'email': widgets.EmailInput(attrs={
                'class': 'form-control w-50'
            }),
            'birth_date': widgets.DateInput(attrs={
                'type': 'date',
                'class': 'form-control w-50'
            }, format='%Y-%m-%d'),
            'avatar': widgets.FileInput(attrs={
                'class': 'form-control rounded-pill mb-3 w-50'
            })
        }


class MyPasswordChangeForm(PasswordChangeForm):
    new_password1 = forms.CharField(label="Новый пароль", strip=False,
                                    widget=forms.PasswordInput(attrs={'class': 'form-control w-50'}))
    new_password2 = forms.CharField(label="Подтвердите пароль",
                                    widget=forms.PasswordInput(attrs={'class': 'form-control w-50'}), strip=False)
    old_password = forms.CharField(label="Старый пароль", strip=False,
                                   widget=forms.PasswordInput(attrs={'class': 'form-control w-50'}))

    class Meta:
        model = get_user_model()

source/accounts/templates/user_add.html
{% extends 'base.html' %}
{% block content %}

    <div class="container-xxl py-3">
        <div class="card">
            <div class="card-body">
                <h1>Добавить пользователя</h1>
                <form action="" method="post">
                    {% include 'partial/form.html' with button_text="Добавить" %}

                </form>
            </div>
        </div>
    </div>
{% endblock %}

source/accounts/templates/user_change.html
{% extends 'base.html' %}
{% block content %}

    <div class="container-xxl py-3">
        <div class="card">
            <div class="card-body">
                <h1>Поменять личные данные</h1>

                <form action="" method="post" enctype="multipart/form-data">
                    {% include 'partial/form.html' with fields_only=True %}
                    {% include 'partial/form.html' with form=profile_form button_text="Изменить" %}

                </form>
            </div>
        </div>
    </div>
{% endblock %}

source/accounts/templates/user_create.html
{% extends 'base.html' %}
{% block content %}

    <div class="container-xxl py-3">
        <div class="card">
            <div class="card-body">
                <h1>Регистрация</h1>
                <form action="" method="post">
                    {% include 'partial/form.html' with button_text="Зарегистрироваться" %}

                </form>
            </div>
        </div>
    </div>
{% endblock %}

source/accounts/templates/user_detail.html
{% extends 'base.html' %}
{% block content %}

    <div class="container-xxl py-3">
        <div class="card mb-3">
            <div class="card-body">
                <h1>Личная страница пользователя {{ user_obj.get_full_name|default:user_obj.username }}</h1>
                <div class="row g-0">
                    {% if user_obj.avatar %}
                        <div class="col-md-4">
                            <img src="{{ user_obj.avatar.url }}" class="img-fluid rounded-start w-75">
                        </div>
                    {% endif %}
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">Имя пользователя: {{ user_obj.username }}</h5>
                            <p class="card-text">Имя: {{ user_obj.first_name|default:'-' }}</p>
                            <p class="card-text">Фамилия: {{ user_obj.last_name|default:'-' }}</p>
                            <p class="card-text">Дата рождения: {{ user_obj.birth_date|date:'d.m.Y'|default:'-' }}</p>
                            <p class="card-text">Почта: {{ user_obj.email|default:'-' }}</p>
                            {% if user_obj == request.user %}
                                <a href="{% url 'accounts:change' %}" role="button"
                                   class="btn btn-outline-success rounded-pill me-2"><i
                                        class="bi bi-pencil-fill me-3"></i>Редактировать</a>
                                <a href="{% url 'accounts:password_change' %}" role="button"
                                   class="btn btn-outline-warning rounded-pill"><i
                                        class="bi bi-pencil-fill me-3"></i>Сменить пароль</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% if not user_obj.is_admin %}
            <div class="card">
                <div class="card-body">
                    <h1>Группы</h1>
                    <div class="row row-cols-3">
                        {% for group in groups %}
                            <div class="col my-3">
                                <div class="card h-100">
                                    <div class="card-body">
                                        <div class="d-flex flex-wrap align-items-center mb-3">
                                            <h5 class="card-title m-0"><a href="{% url 'webapp:group_view' group.pk %}"
                                                                          style="color: {{ group.color }};">{{ group.language.name_language }}
                                                #{{ group.number_group }}</a></h5>
                                        </div>
                                        <p class="card-text">Дата запуска группы: {{ group.data_start }} </p>
                                        {% if group.data_end %}
                                            <p class="card-text">Дата выпуска
                                                группы:{{ group.data_end }} </p>{% endif %}
                                    </div>
                                    {% if user_obj == request.user and request.user.is_student %}
                                        <a class="btn btn-outline-info btn-sm rounded-pill m-2"
                                           href="{% url 'accounts:user_results' group.pk %}"
                                           role="button">Успеваимось</a>
                                    {% endif %}
                                </div>
                            </div>
                        {% endfor %}
                    </div>

                </div>
            </div>
        {% endif %}
    </div>





{% endblock %}

source/accounts/templates/user_list.html
{% extends 'base.html' %}
{% block content %}

    <div class="container-xxl py-3">
        <div class="card">
            <div class="card-body">
                <table class="table table-hover table-striped">
                    <thead>
                    <tr>
                        <th scope="col">Пользователь</th>
                        <th scope="col">Роль</th>
                        <th scope="col">Группы</th>
                        <th scope="col"> Время создание</th>
                        <th scope="col">Дейстивия</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for el in role_and_group %}
                        <tr>

                            <td>{% if el.user %}
                                <a href="{% url 'accounts:detail' el.user.pk %}">{{ el.user.username }}</a>
                            {% else %}-{% endif %}
                            </td>
                            <td>{{ el.get_user_role_display }}</td>
                            <td>{% for group in el.groups.all %}
                                {{ group.language.name_language }}#{{ group.number_group }}
                                {% if  not forloop.last %}, {% endif %}{% endfor %}</td>

                            <td>{{ el.created_at }}</td>
                            <td>
                                {% if el.user %}
                                {% else %}
                                    <a class="btn btn-outline-success btn-sm rounded-pill"
                                       href="{% url 'accounts:create' el.token %}" role="button">Ссылка для
                                        регистрации</a>
                                    <button type="button" class="btn btn-outline-secondary btn-sm rounded-pill"
                                            data-url="{% url 'accounts:create' el.token %}" onclick="myFunction(this)">
                                        Скопировать
                                        ссылку
                                    </button>
                                    <a class="btn btn-outline-danger btn-sm rounded-circle"
                                       href="{% url 'accounts:token_delete' el.pk %}" role="button"><i
                                            class="bi bi-trash"></i></a>

                                {% endif %}
                            </td>

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block my_script %}
    <script>
        function myFunction(e) {
            navigator.clipboard.writeText(host + e.dataset.url);
            }
    </script>
{% endblock %}

source/accounts/templates/user_password_change.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-xxl py-3">
        <div class="card">
            <div class="card-body">
                <h1>Смена пароля</h1>

                <form action="" method="post">
                    {% include 'partial/form.html' with button_text="Изменить" %}

                </form>
            </div>
        </div>
    </div>
{% endblock %}

source/accounts/templates/user_results.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-xxl mt-3">
        <div class="row flex-column">
            <div class="col-4 mb-3">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ group.language.name_language }}
                            #{{ group.number_group }}</h5>
                        <p class="card-text">Дата запуска группы: {{ group.data_start }} </p>
                        {% if group.data_end %}
                            <p class="card-text">Дата выпуска группы:{{ group.data_end }} </p>{% endif %}
                    </div>
                </div>
            </div>
            <div class="col-12">
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title d-inline-block">Периоды </h5>
                        <a class="btn btn-outline-success btn-sm rounded-circle"
                           href="{% url 'webapp:period_create' group.pk %}"
                           role="button"><i class="bi bi-plus-lg"></i></a>
                        <div class="p-1">
                            {% for period in group.periods.all %}
                                <a href="{% url "accounts:user_results_period" group.pk period.pk %}"
                                   class="btn {% if period_now.pk == period.pk %} btn-success disabled
                                  {% else %} btn-outline-secondary {% endif %}">
                                    #{{ period.number_period }}</a>
                            {% endfor %}

                        </div>
                    </div>
                </div>
            </div>
            {% if period_now %}
                <div class="col-12 ">
                    <div class="card">
                        <div class="card-header d-flex">
                            <div class="d-flex align-items-center">
                                <h5 class="mb-0">Учебный месяц №{{ period_now.number_period }} </h5>
                                <span class="ms-3">({{ period_now.data_start|date:"d-m-Y" }}-{{ period_now.data_end|date:"d-m-Y" }})</span>
                            </div>
                            <h5 class="border rounded-pill border-success ms-auto px-2 py-1 mb-0">{{ total_result }}</h5>
                        </div>
                        <div class="row row-cols-{{ lessons_count }} m-2 mb-4">
                            {% for lesson in lessons %}
                                <div class="col my-2">
                                    <div class="card border h-100
                                        {% if lesson.data_start|date:"Ymd" == now|date:"Ymd" %} border-success
                                        {% else %} border-secondary {% endif %}">
                                        <div class="card-header d-flex align-items-center">
                                            <h5 class="mb-0">{{ lesson.get_type_lesson_display }}
                                                #{{ lesson.number }}</h5>
                                        </div>
                                        <div class="card-body">
                                        <h6 class="card-subtitle mb-2 text-muted d-inline-block">
                                            Оценка: </h6>
                                            {% for work in user_works %}
                                                {% if work.lesson == lesson %}
                                                    <h6 class="card-subtitle mb-2 text-muted d-inline-block"> <a href="{% url 'webapp:work_view' work.pk %}"
                                                       class="card-link link-success">{{ work.grade }}</a></h6>
                                                {% endif %}
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                            {% if control %}
                                <div class="col my-2">
                                    <div class="card border h-100
                                        {% if control.data_start|date:"Ymd" == now|date:"Ymd" %} border-success
                                        {% else %} border-secondary {% endif %}">
                                        <div class="card-header d-flex align-items-center">
                                            <h5 class="mb-0">{{ control.get_type_lesson_display }}
                                                #{{ control.number }}</h5>
                                        </div>
                                        <div class="card-body">
                                        <h6 class="card-subtitle mb-2 text-muted d-inline-block">
                                            Оценка: </h6>
                                            {% for work in user_works %}
                                                {% if work.lesson == control %}
                                                    <h6 class="card-subtitle mb-2 text-muted d-inline-block"> <a href="{% url 'webapp:work_view' work.pk %}"
                                                       class="card-link link-success">{{ work.grade }}</a></h6>
                                                {% endif %}
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}