source/accounts/urls.py
from django.urls import path, re_path

from accounts.views import RegisterView, UserDetailView, UserChangeView, UserPasswordChangeView, UserList, UserAdd, \
    TokenDelete, UserResults
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/<str:token>/', RegisterView.as_view(), name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('change/', UserChangeView.as_view(), name='change'),
    path('user/add/', UserAdd.as_view(), name='user_add'),
    path('user/group/<int:group_pk>/results/', UserResults.as_view(), name='user_results'),
    path('user/group/<int:group_pk>/period/<int:period_pk>/results/', UserResults.as_view(), name='user_results_period'),
    path('token/<int:pk>/delete/', TokenDelete.as_view(), name='token_delete'),
    path('password_change/', UserPasswordChangeView.as_view(), name='password_change'),
    path("password_reset/", PasswordResetView.as_view(), name="password_reset"),
    re_path(r'^users/(?P<is_filter>registered|not_registered)/$', UserList.as_view(), name='users_list_is_filter'),
]

source/crm_attractor/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('accounts.urls')),
                  path('', include('webapp.urls')),
                  path('tinymce/', include('tinymce.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views import IndexView, GroupsList, GroupView, LessonView, MaterialView, MaterialList, \
    PeriodCreate, PeriodDelete, LessonCreate, LessonUpdate, LessonDelete, LessonGroupCreate, LanguageCreate, \
    LanguageDelete, GroupCreate, GroupUpdate, GroupDelete, MaterialCreate, MaterialUpdate, MaterialDelete, \
    MaterialSearchCreate, LinkBroadcastCreate, LinkBroadcastDelete, WorkUserCreate, WorkUserUpdate, WorkUserCheck, \
    LessonUpdateDeadlineTask, WorkLessonCheck, PeriodView, WorkView

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('lesson/<int:lesson_pk>/', LessonView.as_view(), name='lesson_view'),
    path('lesson/create/', LessonCreate.as_view(), name='lesson_create'),
    path('lesson/<int:group_pk>/create/', LessonGroupCreate.as_view(), name='lesson_group_create'),
    path('lesson/<int:lesson_pk>/update/', LessonUpdate.as_view(), name='lesson_update'),
    path('lesson/<int:lesson_pk>/update/deadline_task/', LessonUpdateDeadlineTask.as_view(),
         name='lesson_update_deadline_task'),
    path('lesson/<int:lesson_pk>/delete/', LessonDelete.as_view(), name='lesson_delete'),

    path('group/', GroupsList.as_view(), name='groups_list'),
    path('group/<int:group_pk>/', GroupView.as_view(), name='group_view'),
    path('group/<int:group_pk>/period/<int:period_pk>/', GroupView.as_view(), name='group_view_period_pk'),
    path('group/<int:language_pk>/create/', GroupCreate.as_view(), name='group_create'),
    path('group/<int:group_pk>/update/', GroupUpdate.as_view(), name='group_update'),
    path('group/<int:group_pk>/delete/', GroupDelete.as_view(), name='group_delete'),

    path('materials/', MaterialList.as_view(), name='materials_list'),
    path('material/<int:material_pk>/', MaterialView.as_view(), name='material_view'),
    path('material/<int:group_pk>/lesson/<int:lesson_pk>/type/<str:type>/create/', MaterialCreate.as_view(),
         name='material_create'),
    path('material/<int:group_pk>/lesson/<int:lesson_pk>/type/<str:type>/create_search/',
         MaterialSearchCreate.as_view(),
         name='material_search_create'),
    path('material/<int:material_pk>/update/', MaterialUpdate.as_view(), name='material_update'),
    path('material/<int:material_pk>/delete/', MaterialDelete.as_view(), name='material_delete'),

    path('language/create/', LanguageCreate.as_view(), name='language_create'),
    path('language/<int:language_pk>/delete/', LanguageDelete.as_view(), name='language_delete'),

    path('period/create/<int:group_pk>/', PeriodCreate.as_view(), name='period_create'),
    path('period/delete/<int:pk>/', PeriodDelete.as_view(), name='period_delete'),
    path('period/<int:pk>/', PeriodView.as_view(), name='period_results'),

    path('work/<int:pk>/', WorkView.as_view(), name='work_view'),
    path('work/lesson/<int:lesson_pk>/create/', WorkUserCreate.as_view(), name='work_create'),
    path('work/<int:work_pk>/update/', WorkUserUpdate.as_view(), name='work_update'),
    path('work/<int:work_pk>/verification/', WorkUserCheck.as_view(), name='work_check'),
    path('work/lesson/<int:lesson_pk>/lesson_check/', WorkLessonCheck.as_view(), name='work_lesson_check'),

    path('link_broadcast/lesson/<int:lesson_pk>/create/', LinkBroadcastCreate.as_view(),
         name='link_broadcast_create'),
    path('link_broadcast/<int:link_broadcast_pk>/delete/', LinkBroadcastDelete.as_view(),
         name='link_broadcast_delete'),
]

source/webapp/views/groups.py
import datetime

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from webapp.models import Group, Language
from webapp.forms import GroupForm
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404


class GroupsList(LoginRequiredMixin, ListView):
    template_name = 'groups/list.html'
    model = Language
    context_object_name = 'languages'

    def get_queryset(self):
        queryset = super().get_queryset()
        if not self.request.user.is_superuser and not self.request.user.is_admin():
            queryset = queryset.filter(groups__users=self.request.user).distinct()
        return queryset


class GroupView(PermissionRequiredMixin, DetailView):
    template_name = 'groups/view.html'
    model = Group
    pk_url_kwarg = "group_pk"

    def has_permission(self):
        group = get_object_or_404(Group, pk=self.kwargs.get('group_pk'))
        return self.request.user.is_superuser or self.request.user.is_admin() or self.request.user in group.users.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        group = self.object
        periods = group.periods.order_by('data_end')
        context['periods'] = periods
        now = datetime.datetime.now()
        context['period_now'] = None
        context['now'] = now
        period_pk = self.kwargs.get('period_pk', '')
        if period_pk:
            try:
                context['period_now'] = periods.get(pk=period_pk)
            except ObjectDoesNotExist:
                raise Http404()
        else:
            period_now = periods.filter(data_start__lte=now, data_end__gte=now)
            context['period_now'] = periods.first()
            if period_now.count():
                context['period_now'] = period_now.first()
        if context['period_now']:
            context['lessons'] = context['period_now'].lessons.order_by('data_start')
        return context


class GroupCreate(PermissionRequiredMixin, CreateView):
    template_name = 'groups/create.html'
    model = Group
    form_class = GroupForm
    success_url = reverse_lazy('webapp:groups_list')
    pk_url_kwarg = 'language_pk'

    def has_permission(self):
        return self.request.user.is_superuser or self.request.user.is_admin()

    def form_valid(self, form):
        language = get_object_or_404(Language, pk=self.kwargs.get('language_pk'))
        form.instance.language = language
        return super().form_valid(form)


class GroupUpdate(PermissionRequiredMixin, UpdateView):
    template_name = 'groups/update.html'
    model = Group
    form_class = GroupForm
    success_url = reverse_lazy('webapp:groups_list')
    pk_url_kwarg = 'group_pk'

    def has_permission(self):
        return self.request.user.is_superuser or self.request.user.is_admin()


class GroupDelete(PermissionRequiredMixin, DeleteView):
    model = Group
    success_url = reverse_lazy('webapp:groups_list')
    pk_url_kwarg = 'group_pk'

    def has_permission(self):
        return self.request.user.is_superuser or self.request.user.is_admin()

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

source/webapp/views/languages.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic import CreateView, DeleteView

from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404

from webapp.models import Language
from webapp.forms import LanguageForm


class LanguageCreate(PermissionRequiredMixin, CreateView):
    template_name = 'languages/create.html'
    model = Language
    form_class = LanguageForm
    success_url = reverse_lazy('webapp:groups_list')

    def has_permission(self):
        return self.request.user.is_superuser or self.request.user.is_admin()


class LanguageDelete(PermissionRequiredMixin, DeleteView):
    model = Language
    success_url = reverse_lazy('webapp:groups_list')
    pk_url_kwarg = 'language_pk'

    def has_permission(self):
        language = get_object_or_404(Language, pk=self.kwargs.get('language_pk'))
        return not language.groups.all() and (self.request.user.is_superuser or self.request.user.is_admin())

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

source/webapp/views/lessons.py
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView, TemplateView
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.utils.safestring import mark_safe
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from webapp.utils import Calendar
from webapp.forms import LessonForm, LessonGroupForm, WorkUserForm
from webapp.models import Lesson, Period, Group, TYPE_CONTROL

from datetime import datetime, date


def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return date(year, month, day=1)
    return datetime.today()


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        d = get_date(self.request.GET.get('day', None))
        event_queryset = None
        if self.request.user.is_admin():
            event_queryset = Lesson.objects.all()
        else:
            event_queryset = Lesson.objects.filter(period__group__users=self.request.user)
        cal = Calendar(d.year, d.month, event_queryset,
                       self.request.user.is_superuser or self.request.user.is_admin() or self.request.user.is_teacher())

        html_cal = cal.formatmonth(withyear=True)

        context['calendar'] = mark_safe(html_cal)
        return context


class LessonView(PermissionRequiredMixin, DetailView):
    template_name = 'lessons/view.html'
    model = Lesson
    pk_url_kwarg = "lesson_pk"

    def has_permission(self):
        lesson = get_object_or_404(Lesson, pk=self.kwargs.get('lesson_pk'))
        return self.request.user.is_superuser or self.request.user.is_admin() \
            or self.request.user in lesson.period.group.users.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_work'] = self.object.lesson_works.filter(user=self.request.user).first()
        context['form'] = WorkUserForm()
        context['works_count'] = self.object.lesson_works.filter(status=False).count()
        if context['user_work']:
            context['form'] = WorkUserForm(instance=context['user_work'])
        return context


class LessonCreate(PermissionRequiredMixin, CreateView):
    template_name = 'lessons/create.html'
    model = Lesson
    form_class = LessonForm

    def has_permission(self):
        return self.request.user.is_superuser or self.request.user.is_admin() or self.request.user.is_teacher()

    def get_success_url(self):
        return self.request.GET.get('next_url', reverse('webapp:index'))

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if self.request.user.is_teacher():
            kwargs.update({"filter_group_users": [self.request.user]})
        return kwargs

    def form_valid(self, form):
        period = Period.objects.filter(data_start__lte=form.cleaned_data['data_start'],
                                       data_end__gte=form.cleaned_data['data_start'],
                                       group=form.cleaned_data['group']).first()
        form.instance.period = period
        last_lesson = Lesson.objects.filter(type_lesson=form.cleaned_data['type_lesson'],
                                            data_start__lte=form.cleaned_data['data_start'],
                                            period__in=form.cleaned_data['group'].periods.all()).order_by(
            'number').last()
        number_lesson = 1
        if last_lesson:
            number_lesson += last_lesson.number

        form.instance.number = number_lesson

        return super().form_valid(form)


class LessonGroupCreate(PermissionRequiredMixin, CreateView):
    template_name = 'lessons/create.html'
    model = Lesson
    form_class = LessonGroupForm

    def has_permission(self):
        group = get_object_or_404(Group, pk=self.kwargs.get('group_pk'))
        return self.request.user.is_superuser or self.request.user.is_admin() or self.request.user.is_teacher() and self.request.user in group.users.all()

    def get_success_url(self):
        return reverse('webapp:group_view_period_pk',
                       kwargs={'group_pk': self.object.period.group.pk, 'period_pk': self.object.period.pk})

    def form_valid(self, form):
        group = get_object_or_404(Group, pk=self.kwargs.get('group_pk'))
        period = Period.objects.filter(data_start__lte=form.cleaned_data['data_start'],
                                       data_end__gte=form.cleaned_data['data_start'],
                                       group=group).first()
        form.instance.group = group
        form.instance.period = period
        if form.cleaned_data['type_lesson'] != TYPE_CONTROL:
            last_lesson = Lesson.objects.filter(type_lesson=form.cleaned_data['type_lesson'],
                                                data_start__lte=form.cleaned_data['data_start'],
                                                period__in=group.periods.all()).order_by(
                'number').last()
        else:
            last_lesson = Lesson.objects.filter(type_lesson=form.cleaned_data['type_lesson'],
                                                data_start__lte=form.cleaned_data['data_start']).order_by(
                'number').last()
        number_lesson = 1
        if last_lesson:
            number_lesson += last_lesson.number

        form.instance.number = number_lesson

        return super().form_valid(form)


class LessonUpdate(PermissionRequiredMixin, UpdateView):
    template_name = 'lessons/create.html'
    model = Lesson
    form_class = LessonGroupForm
    pk_url_kwarg = "lesson_pk"

    def has_permission(self):
        group = get_object_or_404(Lesson, pk=self.kwargs.get('lesson_pk')).period.group
        return self.request.user.is_superuser or self.request.user.is_admin() or self.request.user.is_teacher() and self.request.user in group.users.all()

    def get_success_url(self):
        return self.request.GET.get('next_url', reverse('webapp:lesson_view', kwargs={'lesson_pk': self.object.pk}))


class LessonUpdateDeadlineTask(PermissionRequiredMixin, UpdateView):
    model = Lesson
    pk_url_kwarg = "lesson_pk"
    fields = ['deadline_task']

    def has_permission(self):
        group = get_object_or_404(Lesson, pk=self.kwargs.get('lesson_pk')).period.group
        return self.request.user.is_superuser or self.request.user.is_admin() or self.request.user.is_teacher() and self.request.user in group.users.all()

    def get_success_url(self):
        return self.request.GET.get('next_url', reverse('webapp:lesson_view', kwargs={'lesson_pk': self.object.pk}))


class LessonDelete(PermissionRequiredMixin, DeleteView):
    model = Lesson
    pk_url_kwarg = "lesson_pk"

    def has_permission(self):
        group = get_object_or_404(Lesson, pk=self.kwargs.get('lesson_pk')).period.group
        return self.request.user.is_superuser or self.request.user.is_admin() or self.request.user.is_teacher() and self.request.user in group.users.all()

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def get_success_url(self):
        return self.request.GET.get('next_url', reverse('webapp:index'))

source/webapp/templates/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}CRM Attractor{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% if request.user.is_authenticated %}{% url 'webapp:index' %}{% endif %}">
            <img src="{% static 'images/attractor-logo.png' %}" alt="" width="30" height="24"
                 class="d-inline-block align-text-top">
            Attractor School
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link {% url 'webapp:index' as profile_url %} {% if request.path == profile_url %}active{% endif %}"
                           aria-current="page" href="{% url 'webapp:index' %}">События</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% url 'webapp:groups_list' as profile_url %} {% if request.path == profile_url %}active{% endif %}"
                           aria-current="page" href="{% url 'webapp:groups_list' %}">Группы</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% url 'webapp:materials_list' as profile_url %} {% if request.path == profile_url %}active{% endif %}"
                           aria-current="page" href="{% url 'webapp:materials_list' %}">Материалы</a>
                    </li>
                    {% block menu %}
                    {% endblock %}
                {% endif %}
            </ul>
            {% if request.user.is_authenticated %}
                {% if request.user.is_admin %}
                    <div class="nav-item dropdown">
                        <a class="nav-link text-secondary dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown"
                           aria-expanded="false">
                            <i class="bi bi-people-fill"></i>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'accounts:users_list_is_filter' 'registered' %}">Зарегистрированные</a>
                            </li>
                            <li><a class="dropdown-item"
                                   href="{% url 'accounts:users_list_is_filter' 'not_registered' %}">Не
                                Зарегистрированные</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'accounts:user_add' %}">Добавить пользователя</a>
                            </li>
                        </ul>
                    </div>
                {% endif %}
                <a href="{% url 'accounts:detail' request.user.pk %}"
                   class="navbar-text lh-base mb-0 me-3 text-capitalize
                      text-decoration-none fw-bolder">Профиль</a>
                <a href="{% url 'accounts:logout' %}" class="btn btn-outline-success navbar-text me-5">Выйти</a>
            {% endif %}
        </div>


    </div>
</nav>

{% block content %}
{% endblock %}
<script src="{% static 'js/bootstrap.bundle.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

{% block my_script %}
{% endblock %}
</body>
</html>

source/webapp/templates/index.html
{% extends 'base.html' %}

{% block content %}
    {{ calendar }}
{% endblock %}