source/crm_attractor/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('accounts.urls')),
                  path('', include('webapp.urls')),
                  path('tinymce/', include('tinymce.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views import IndexView, GroupsList, GroupView, LessonView, MaterialView, MaterialList, \
    PeriodCreate, PeriodDelete, LessonCreate, LessonUpdate, LessonDelete, LessonGroupCreate, LanguageCreate, \
    LanguageDelete, GroupCreate, GroupUpdate, GroupDelete, MaterialCreate, MaterialUpdate, MaterialDelete, \
    MaterialSearchCreate, LinkBroadcastCreate, LinkBroadcastDelete, WorkUserCreate, WorkUserUpdate, WorkUserCheck, \
    LessonUpdateDeadlineTask, WorkLessonCheck, PeriodView, WorkView

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('lesson/<int:lesson_pk>/', LessonView.as_view(), name='lesson_view'),
    path('lesson/create/', LessonCreate.as_view(), name='lesson_create'),
    path('lesson/<int:group_pk>/create/', LessonGroupCreate.as_view(), name='lesson_group_create'),
    path('lesson/<int:lesson_pk>/update/', LessonUpdate.as_view(), name='lesson_update'),
    path('lesson/<int:lesson_pk>/update/deadline_task/', LessonUpdateDeadlineTask.as_view(),
         name='lesson_update_deadline_task'),
    path('lesson/<int:lesson_pk>/delete/', LessonDelete.as_view(), name='lesson_delete'),

    path('group/', GroupsList.as_view(), name='groups_list'),
    path('group/<int:group_pk>/', GroupView.as_view(), name='group_view'),
    path('group/<int:group_pk>/period/<int:period_pk>/', GroupView.as_view(), name='group_view_period_pk'),
    path('group/<int:language_pk>/create/', GroupCreate.as_view(), name='group_create'),
    path('group/<int:group_pk>/update/', GroupUpdate.as_view(), name='group_update'),
    path('group/<int:group_pk>/delete/', GroupDelete.as_view(), name='group_delete'),

    path('materials/', MaterialList.as_view(), name='materials_list'),
    path('material/<int:material_pk>/', MaterialView.as_view(), name='material_view'),
    path('material/<int:group_pk>/lesson/<int:lesson_pk>/type/<str:type>/create/', MaterialCreate.as_view(),
         name='material_create'),
    path('material/<int:group_pk>/lesson/<int:lesson_pk>/type/<str:type>/create_search/',
         MaterialSearchCreate.as_view(),
         name='material_search_create'),
    path('material/<int:material_pk>/update/', MaterialUpdate.as_view(), name='material_update'),
    path('material/<int:material_pk>/delete/', MaterialDelete.as_view(), name='material_delete'),

    path('language/create/', LanguageCreate.as_view(), name='language_create'),
    path('language/<int:language_pk>/delete/', LanguageDelete.as_view(), name='language_delete'),

    path('period/create/<int:group_pk>/', PeriodCreate.as_view(), name='period_create'),
    path('period/delete/<int:pk>/', PeriodDelete.as_view(), name='period_delete'),
    path('period/<int:pk>/', PeriodView.as_view(), name='period_results'),

    path('work/<int:pk>/', WorkView.as_view(), name='work_view'),
    path('work/lesson/<int:lesson_pk>/create/', WorkUserCreate.as_view(), name='work_create'),
    path('work/<int:work_pk>/update/', WorkUserUpdate.as_view(), name='work_update'),
    path('work/<int:work_pk>/verification/', WorkUserCheck.as_view(), name='work_check'),
    path('work/lesson/<int:lesson_pk>/lesson_check/', WorkLessonCheck.as_view(), name='work_lesson_check'),

    path('link_broadcast/lesson/<int:lesson_pk>/create/', LinkBroadcastCreate.as_view(),
         name='link_broadcast_create'),
    path('link_broadcast/<int:link_broadcast_pk>/delete/', LinkBroadcastDelete.as_view(),
         name='link_broadcast_delete'),
]

source/webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Language(models.Model):
    name_language = models.CharField(max_length=200, unique=True, verbose_name='Название языка')

    def __str__(self):
        return "{}. {}".format(self.pk, self.name_language)


class Group(models.Model):
    number_group = models.IntegerField(verbose_name='Номер группы')
    data_start = models.DateField(verbose_name='Дата запуска группы')
    color = models.CharField(max_length=20, verbose_name="Цвет группы")
    data_end = models.DateField(null=True, blank=True, verbose_name='Дата выпуска группы')
    language = models.ForeignKey('webapp.Language', related_name='groups', on_delete=models.PROTECT,
                                 verbose_name='Язык')
    users = models.ManyToManyField(get_user_model(), related_name='groups_language', through='webapp.GroupUser',
                                   through_fields=('group', 'user'), blank=True)
    is_activation = models.BooleanField(default=True)

    def __str__(self):
        return "{}№{} ({}-{}) ".format(self.language.name_language, self.number_group, self.data_start, self.data_end)


class Period(models.Model):
    number_period = models.IntegerField(verbose_name='Номер периода')
    data_start = models.DateField(verbose_name='Дата начала периода')
    data_end = models.DateField(verbose_name='Дата окончания периода')
    group = models.ForeignKey('webapp.Group', related_name='periods', on_delete=models.PROTECT,
                              verbose_name='Группа')

    def __str__(self):
        return "{}. {} #{}  ({}-{})".format(self.pk, self.group, self.number_period, self.data_start, self.data_end)


TYPE_TASK = 'task'
TYPE_MATERIAL = 'material'
TYPES_MATERIAL = [
    (TYPE_TASK, 'Задание'),
    (TYPE_MATERIAL, 'Материал'),
]


class Material(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    content = models.TextField(null=True, blank=True, verbose_name='Содержимое')
    group = models.ForeignKey('webapp.Group', related_name='material', on_delete=models.PROTECT,
                              verbose_name='Группа')
    lesson = models.ForeignKey('webapp.Lesson', on_delete=models.PROTECT, related_name='materials', verbose_name='Урок')
    type_material = models.CharField(choices=TYPES_MATERIAL, max_length=20, verbose_name='Тип')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Время изменения")

    def __str__(self):
        return "{}. {}".format(self.pk, self.title)


TYPE_LESSON = 'lesson'
TYPE_WEBINAR = 'webinar'
TYPE_CONTROL = 'control'
CHOICES_TYPES_LESSON = ((TYPE_LESSON, 'Занятие'), (TYPE_WEBINAR, 'Вебинар'), (TYPE_CONTROL, 'Контрольная'))


class Lesson(models.Model):
    number = models.IntegerField(default=1, verbose_name='Номер урока')
    data_start = models.DateTimeField(verbose_name='Время начала урока')
    theme = models.CharField(max_length=200, null=True, blank=True, verbose_name='Тема урока')
    deadline_task = models.DateTimeField(null=True, blank=True, verbose_name='Дедлайн задания')
    type_lesson = models.CharField(choices=CHOICES_TYPES_LESSON, null=True, verbose_name='Тип урока')
    period = models.ForeignKey('webapp.Period', related_name='lessons', on_delete=models.PROTECT,
                               verbose_name='Период')

    def __str__(self):
        return "{}. {} ({})".format(self.pk, self.theme, self.data_start)

    def get_razdatka(self):
        return self.materials.filter(type_material=TYPE_MATERIAL).order_by('-created_at').first()

    def get_task(self):
        return self.materials.filter(type_material=TYPE_TASK).order_by('-created_at').first()


class LinkBroadcast(models.Model):
    link = models.CharField(max_length=200, verbose_name='Ссылка')
    lesson = models.ForeignKey('webapp.Lesson', related_name='links_broadcast', on_delete=models.PROTECT,
                               verbose_name='Урок')

    def __str__(self):
        return "{}. {}".format(self.pk, self.link)


class Work(models.Model):
    grade = models.FloatField(verbose_name='Оценка', default=0)
    work = models.FileField(null=True, blank=True, verbose_name='Файл')
    link = models.CharField(max_length=200, null=True, blank=True, verbose_name='Ссылка')
    review = models.TextField(null=True, blank=True, verbose_name='Рецензия')
    lesson = models.ForeignKey('webapp.Lesson', related_name='lesson_works', on_delete=models.CASCADE,
                               verbose_name='Урок')
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='user_works',
                             verbose_name='Пользователь')
    status = models.BooleanField(default=False, verbose_name='Проверена')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Время загрузки")


class GroupUser(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='user_groups',
                             verbose_name='Пользователь')
    group = models.ForeignKey('webapp.Group', related_name='group_users', on_delete=models.PROTECT,
                              verbose_name='Группа')
    data_start = models.DateField(verbose_name='Дата начала учебы')
    data_end = models.DateField(null=True, blank=True, verbose_name='Дата окончания учебы')

source/webapp/views/groups.py
import datetime

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from webapp.models import Group, Language
from webapp.forms import GroupForm
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404


class GroupsList(LoginRequiredMixin, ListView):
    template_name = 'groups/list.html'
    model = Language
    context_object_name = 'languages'

    def get_queryset(self):
        queryset = super().get_queryset()
        if not self.request.user.is_superuser and not self.request.user.is_admin():
            queryset = queryset.filter(groups__users=self.request.user).distinct()
        return queryset


class GroupView(PermissionRequiredMixin, DetailView):
    template_name = 'groups/view.html'
    model = Group
    pk_url_kwarg = "group_pk"

    def has_permission(self):
        group = get_object_or_404(Group, pk=self.kwargs.get('group_pk'))
        return self.request.user.is_superuser or self.request.user.is_admin() or self.request.user in group.users.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        group = self.object
        periods = group.periods.order_by('data_end')
        context['periods'] = periods
        now = datetime.datetime.now()
        context['period_now'] = None
        context['now'] = now
        period_pk = self.kwargs.get('period_pk', '')
        if period_pk:
            try:
                context['period_now'] = periods.get(pk=period_pk)
            except ObjectDoesNotExist:
                raise Http404()
        else:
            period_now = periods.filter(data_start__lte=now, data_end__gte=now)
            context['period_now'] = periods.first()
            if period_now.count():
                context['period_now'] = period_now.first()
        if context['period_now']:
            context['lessons'] = context['period_now'].lessons.order_by('data_start')
        return context


class GroupCreate(PermissionRequiredMixin, CreateView):
    template_name = 'groups/create.html'
    model = Group
    form_class = GroupForm
    success_url = reverse_lazy('webapp:groups_list')
    pk_url_kwarg = 'language_pk'

    def has_permission(self):
        return self.request.user.is_superuser or self.request.user.is_admin()

    def form_valid(self, form):
        language = get_object_or_404(Language, pk=self.kwargs.get('language_pk'))
        form.instance.language = language
        return super().form_valid(form)


class GroupUpdate(PermissionRequiredMixin, UpdateView):
    template_name = 'groups/update.html'
    model = Group
    form_class = GroupForm
    success_url = reverse_lazy('webapp:groups_list')
    pk_url_kwarg = 'group_pk'

    def has_permission(self):
        return self.request.user.is_superuser or self.request.user.is_admin()


class GroupDelete(PermissionRequiredMixin, DeleteView):
    model = Group
    success_url = reverse_lazy('webapp:groups_list')
    pk_url_kwarg = 'group_pk'

    def has_permission(self):
        return self.request.user.is_superuser or self.request.user.is_admin()

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

source/webapp/views/languages.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic import CreateView, DeleteView

from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404

from webapp.models import Language
from webapp.forms import LanguageForm


class LanguageCreate(PermissionRequiredMixin, CreateView):
    template_name = 'languages/create.html'
    model = Language
    form_class = LanguageForm
    success_url = reverse_lazy('webapp:groups_list')

    def has_permission(self):
        return self.request.user.is_superuser or self.request.user.is_admin()


class LanguageDelete(PermissionRequiredMixin, DeleteView):
    model = Language
    success_url = reverse_lazy('webapp:groups_list')
    pk_url_kwarg = 'language_pk'

    def has_permission(self):
        language = get_object_or_404(Language, pk=self.kwargs.get('language_pk'))
        return not language.groups.all() and (self.request.user.is_superuser or self.request.user.is_admin())

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

source/webapp/views/link_broadcast.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic import CreateView, DeleteView
from webapp.models import LinkBroadcast, Lesson
from webapp.forms import LinkBroadcastForm
from django.shortcuts import get_object_or_404
from django.urls import reverse


class LinkBroadcastCreate(PermissionRequiredMixin, CreateView):
    model = LinkBroadcast
    form_class = LinkBroadcastForm

    def has_permission(self):
        group = get_object_or_404(Lesson, pk=self.kwargs.get('lesson_pk')).period.group
        return self.request.user.is_superuser or self.request.user.is_admin() or self.request.user.is_teacher() and self.request.user in group.users.all()

    def form_valid(self, form):
        lesson = get_object_or_404(Lesson, pk=self.kwargs.get('lesson_pk'))
        form.instance.lesson = lesson

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:lesson_view', kwargs={'lesson_pk': self.object.lesson.pk})


class LinkBroadcastDelete(PermissionRequiredMixin, DeleteView):
    model = LinkBroadcast
    pk_url_kwarg = "link_broadcast_pk"

    def has_permission(self):
        group = get_object_or_404(LinkBroadcast, pk=self.kwargs.get('link_broadcast_pk')).lesson.period.group
        return self.request.user.is_superuser or self.request.user.is_admin() or self.request.user.is_teacher() and self.request.user in group.users.all()

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('webapp:lesson_view', kwargs={'lesson_pk': self.object.lesson.pk})

source/webapp/templates/groups/create.html
{% extends 'base.html' %}
{% block content %}

    <div class="container-xxl mt-3">
        <div class="card">
            <div class="card-body">
                <h1>Создание группы</h1>

                <form action="" method="post">
                    {% include 'partial/form.html' with button_text="Создать" %}

                </form>
            </div>
        </div>
    </div>
{% endblock %}

source/webapp/templates/groups/list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-xxl mt-3">
        <div class="accordion accordion-flush" id="accordionFlushExample">
            {% for language in languages %}
                <div class="accordion-item">
                    <div class="accordion-header d-flex" id="{{ language.name_language }}-{{ language.pk }}-heading">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#{{ language.name_language }}-{{ language.pk }}-collapse"
                                aria-expanded="false"
                                aria-controls="{{ language.name_language }}-{{ language.pk }}-collapse">
                            {{ language.name_language }}
                        </button>
                        {% if not language.groups.all %}
                            <div class="pe-3 d-flex align-items-center">
                                <div>
                                    <a class="btn btn-outline-danger btn-sm rounded-circle"
                                       href="{% url 'webapp:language_delete' language.pk %}" role="button"><i
                                            class="bi bi-trash"></i></a>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                    <div id="{{ language.name_language }}-{{ language.pk }}-collapse"
                         class="accordion-collapse collapse p-3"
                         aria-labelledby="{{ language.name_language }}-{{ language.pk }}-heading"
                         data-bs-parent="#accordionFlushExample">

                        <div class="row row-cols-3">
                            {% for group in language.groups.all %}
                                {% if request.user.is_superuser or self.request.user.is_admin or request.user in group.users.all %}
                                    <div class="col my-3">
                                        <div class="card h-100">
                                            <div class="card-body">
                                            <div class="d-flex flex-wrap align-items-center mb-3">
                                                <h5 class="card-title m-0"><a href="{% url 'webapp:group_view' group.pk %}"
                                                                          style="color: {{ group.color }};">{{ group.language.name_language }}
                                                    #{{ group.number_group }}</a></h5>
                                                {% if request.user.is_superuser or self.request.user.is_admin %}
                                                    <a class="btn btn-outline-info btn-sm rounded-circle m-2"
                                                       href="{% url 'webapp:group_update' group.pk %}"
                                                       role="button"> <i class="bi bi-pencil-fill"></i></a>
                                                    <a class="btn btn-outline-danger btn-sm rounded-circle my-2"
                                                       href="{% url 'webapp:group_delete' group.pk %}"
                                                       role="button"> <i class="bi bi-trash"></i></a>
                                                {% endif %}
                                            </div>
                                                <p class="card-text">Дата запуска группы: {{ group.data_start }} </p>
                                                {% if group.data_end %}
                                                    <p class="card-text">Дата выпуска
                                                        группы:{{ group.data_end }} </p>{% endif %}
                                            </div>
                                        </div>
                                    </div>
                                {% endif %}
                            {% endfor %}
                            {% if request.user.is_superuser or self.request.user.is_admin %}
                                <div class="col my-3">
                                    <a class="btn btn-outline-success btn-lg h-100 d-flex align-items-center justify-content-center"
                                       href="{% url 'webapp:group_create' language.pk %}" role="button"><i
                                            class="bi bi-plus-lg fs-1"></i></a>
                                </div>
                            {% endif %}

                        </div>
                    </div>

                </div>
            {% endfor %}
        </div>
        {% if request.user.is_superuser or self.request.user.is_admin %}
            <div class="d-flex my-3">
                <a class="btn btn-success btn-lg rounded-circle fs-2 ms-auto" href="{% url 'webapp:language_create' %}"
                   role="button"><i class="bi bi-plus-lg"></i></a>
            </div>
        {% endif %}
    </div>
{% endblock %}

source/webapp/templates/groups/update.html
{% extends 'base.html' %}
{% block content %}

    <div class="container-xxl mt-3">
        <div class="card">
            <div class="card-body">
                <h1>Изменение группы</h1>

                <form action="" method="post">
                    {% include 'partial/form.html' with button_text="Изменить" %}

                </form>
            </div>
        </div>
    </div>
{% endblock %}

source/webapp/templates/groups/view.html
{% extends 'base.html' %}


{% block content %}
    <div class="container-xxl mt-3">
        <div class="row flex-column">
            <div class="col-4 mb-3">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ group.language.name_language }}
                            #{{ group.number_group }}</h5>
                        <p class="card-text">Дата запуска группы: {{ group.data_start }} </p>
                        {% if group.data_end %}
                            <p class="card-text">Дата выпуска группы:{{ group.data_end }} </p>{% endif %}
                    </div>
                </div>
            </div>
            <div class="col-12">
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title d-inline-block">Периоды </h5>
                        {% if request.user.is_superuser or self.request.user.is_admin or request.user.is_teacher %}
                            <a class="btn btn-outline-success btn-sm rounded-circle"
                               href="{% url 'webapp:period_create' group.pk %}"
                               role="button"><i class="bi bi-plus-lg"></i></a>
                        {% endif %}
                        <div class="p-1">
                            {% for period in periods %}
                                <a href="{% url "webapp:group_view_period_pk" group.pk period.pk %}"
                                   class="btn {% if period_now.pk == period.pk %} btn-success disabled
                                  {% else %} btn-outline-secondary {% endif %}">
                                    #{{ period.number_period }}</a>
                            {% endfor %}

                        </div>
                    </div>
                </div>
            </div>
        {% if period_now %}
            <div class="col-12 ">
                <div class="card">
                    <div class="card-header">
                        <div class="d-flex align-items-center mb-3">
                            <h5 class="mb-0">Учебный месяц №{{ period_now.number_period }} </h5>
                            {% if request.user.is_superuser or self.request.user.is_admin or request.user.is_teacher %}
                                <a class="btn btn-outline-danger btn-sm rounded-circle ms-2"
                                   href="{% url 'webapp:period_delete' period_now.pk %}" role="button"><i
                                        class="bi bi-trash"></i></a>
                                <a class="btn btn-outline-info btn-sm rounded-pill ms-auto"
                                    href="{% url 'webapp:period_results' period_now.pk %}" role="button">Успеваемость</a>
                            {% endif %}
                        </div>


                        <p class="card-text">Дата начала: {{ period_now.data_start|date:"M d, Y" }} </p>
                        <p class="card-text">Дата конца: {{ period_now.data_end|date:"M d, Y" }} </p>
                    </div>
                    <div class="row row-cols-4 m-2 mb-4">
                        {% for lesson in lessons %}
                            <div class="col my-2">
                                <div class="card border h-100
                                        {% if lesson.data_start|date:"Ymd" == now|date:"Ymd" %} border-success
                                        {% else %} border-secondary {% endif %}">
                                    <div class="card-header d-flex align-items-center">
                                        <h5 class="mb-0">{{ lesson.get_type_lesson_display }} #{{ lesson.number }}</h5>
                                        {% if request.user.is_superuser or self.request.user.is_admin or request.user.is_teacher %}
                                            <a class="btn btn-outline-info btn-sm rounded-circle ms-auto me-2"
                                               href="{% url 'webapp:lesson_update' lesson.pk %}?next_url={{ request.path }}"
                                               role="button">
                                                <i class="bi bi-pencil-fill"></i></a>
                                            <a class="btn btn-outline-danger btn-sm rounded-circle"
                                               href="{% url 'webapp:lesson_delete' lesson.pk %}?next_url={{ request.path }}"
                                               role="button">
                                                <i class="bi bi-trash"></i></a>
                                        {% endif %}
                                    </div>
                                    <div class="card-body">

                                        <h6 class="card-subtitle mb-2 text-muted">Начало занятия: <span
                                                class="d-block">{{ lesson.data_start|date:"M d, Y | G:i " }}</span></h6>
                                        <p class="card-text ">Тема: <span
                                                class="d-block fs-5 mt-1">{{ lesson.theme|default:"-" }}</span></p>
                                        {% if lesson.data_start|date:"YmdGi" <= now|date:"YmdGi" %}
                                            <a href="{% url 'webapp:lesson_view' lesson.pk %}"
                                               class="card-link link-success">Просмотреть </a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                        {% if request.user.is_superuser or self.request.user.is_admin or request.user.is_teacher %}
                            <div class="col my-2">
                                <a class="btn btn-outline-success btn-lg h-100 w-100 d-flex align-items-center justify-content-center"
                               href="{% url 'webapp:lesson_group_create' group.pk %}" role="button"><i
                                    class="bi bi-plus-lg fs-1"></i></a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endif %}
        </div>
    </div>
{% endblock %}